zuul:
  ignored-services: '*'
  sensitiveHeaders:
  routes:
    oauth:
      path: /api-o/**
      serviceId: http://www.ityouknow.com/



    budgetQL:
      path: /graphql
      serviceId: budject









