logging:
  level:
    root: info
    com.cloud: debug



mybatis:
  type-aliases-package: com.cloud.modle.apimodle.user
  mapper-locations: classpath:/mybatis-mappers/*
  configuration:
    mapUnderscoreToCamelCase: true
