
spring:
  application:
    name: manage-backend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.111.237.66:3306/paas?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      registry-fetch-interval-seconds: 5