server:
  port: 0
spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zuyunbo/paas          # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 460895202@qq.com                                            # git仓库的账号
          password: zuyunbo123
